# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe InteractionsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Interaction. As you add validations to Interaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      notes: 'My note',
      key_take_aways: 'My key take away',
      follow_ups: 'My follow up',
      location: 'the location',
      private_interaction: false
    }
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  let(:user) { FactoryBot.create(:user) }
  let(:person) { user.people.first }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InteractionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: { user_id: user.id, person_id: person.id }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      interaction = Interaction.create! user_id: user.id, person_id: person.id, **valid_attributes
      get :edit, params: { user_id: user.id, person_id: person.id, id: interaction.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Interaction' do
        expect do
          post :create, params: {  user_id: user.id, person_id: person.id, interaction: valid_attributes }, session: valid_session
        end.to change(Interaction, :count).by(1)
      end

      it 'redirects to the created interaction' do
        post :create, params: { user_id: user.id, person_id: person.id, interaction: valid_attributes }, session: valid_session
        expect(response).to redirect_to user_person_path(user, person)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { user_id: user.id, person_id: person.id, interaction: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        {
          location: 'Basel'
        }
      end

      it 'updates the requested interaction' do
        interaction = Interaction.create! user_id: user.id, person_id: person.id, **valid_attributes
        put :update, params: { user_id: user.id, person_id: person.id, id: interaction.to_param, interaction: new_attributes }, session: valid_session
        interaction.reload
        expect(interaction.location).to eq(new_attributes[:location])
      end

      it 'redirects to the interaction' do
        interaction = Interaction.create! user_id: user.id, person_id: person.id, **valid_attributes
        put :update, params: { user_id: user.id, person_id: person.id, id: interaction.to_param, interaction: valid_attributes }, session: valid_session
        expect(response).to redirect_to user_person_path(user, person)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        interaction = Interaction.create! user_id: user.id, person_id: person.id, **valid_attributes
        put :update, params: { user_id: user.id, person_id: person.id, id: interaction.to_param, interaction: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested interaction' do
      interaction = Interaction.create! user_id: user.id, person_id: person.id, **valid_attributes
      expect do
        delete :destroy, params: { user_id: user.id, person_id: person.id, id: interaction.to_param }, session: valid_session
      end.to change(Interaction, :count).by(-1)
    end

    it 'redirects to the interactions list' do
      interaction = Interaction.create! user_id: user.id, person_id: person.id, **valid_attributes
      delete :destroy, params: { user_id: user.id, person_id: person.id, id: interaction.to_param }, session: valid_session
      expect(response).to redirect_to user_person_path(user, person)
    end
  end
end
